### ISSUE TITLE
Remove (some?) metadata

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tszip#33]
For tsinferred tree sequences, we have started to stuff quite a lot of information into the metadata fields, e.g. `ancestor_data_id`, `sample_data_id`, etc. This is not necessary for lossy representation of the data, and there should probably be an option to remove it. We might also want to other sorts of metadata (e.g. for mutations, possibly even for nodes), and perhaps remove provenance, tree-sequence-level metadata, etc. I'm guessing we would have extra parameters to `.compress()` that would do this.

The reason I ask is that it would be nice to have some way of constructing a "minimal" TS file that simply reconstructs the sites x samples matrix. I could use this to test how well we think inference is doing, in terms of compression.

**Comment by petrelharp** [comment]
Seems like this should be an option in tsinfer, instead?

**Comment by jeromekelleher** [comment]
Yes, I agree, tszip shouldn't need to make any semantic choices about the tree sequence.

**Comment by hyanwong** [comment]
> Yes, I agree, tszip shouldn't need to make any semantic choices about the tree sequence.

Although tszip can be asked to throw away node times, can't it? Is throwing away metadata different?

**Comment by benjeffery** [comment]
Are you talking about the `variants_only` option? It doesn't remove all the times, but does a kind of quantisation:
```python
        ts = ts.simplify(reduce_to_site_topology=True)
        tables = ts.tables
        time = np.unique(tables.nodes.time)
        node_time = np.searchsorted(time, tables.nodes.time)
```

**Comment by hyanwong** [comment]
> Are you talking about the `variants_only` option? It doesn't remove all the times, but does a kind of quantisation:

Yes, sorry, I thought it removed the times entirely, but I guess it just swaps them for integers. My question is, do we want an option to tweak other stuff that might carry out lossy compression on a TS (e.g. metadata, or perhaps other stuff?). It sounds like both Jerome and Peter thing this is different, but I'm not sure it's a tsinfer thing - we might want to remove metadata put in there by e.g. SLiM too. Or by any arbitrary ts-generating process.

**Comment by jeromekelleher** [comment]
Yes, I see, I forgot about the ``variants_only`` option. Maybe this is similar.

**Comment by benjeffery** [comment]
Maybe as these operations aren't to do with compression they could be moved to a method in tskit. Something like `tc.strip` that has various boolean flags?

**Comment by hyanwong** [comment]
I feel that they are a bit like lossy compression. But if there is a `ts.strip()` function, we could pass on options from `compress(lossy=True, ...)` (or whatever) to `ts.strip()` internally. I don't know how/where node times fit into this, though.

**Comment by petrelharp** [comment]
Just plain removing metadata columns feels a bit different than lossy compression (it's like compressing lossily by cropping the image?) - I like the `tskit.strip()` proposal if you need it. This isn't something I've been wanting to do, though.

**Comment by jeromekelleher** [comment]
I think a method for dropping metadata in tskit would be possibly be useful. It's not compression, though, IMO.
