### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'head'

### ISSUE THREAD

**Issue by msmscrz** [tskit-dev/tszip#34]
Hello, I'm new to coding and a new assignment recently requires me to perform association rules mining. I'm getting the following error and would like some help to resolve it.

![image](https://user-images.githubusercontent.com/74415626/99080276-0d4bf480-25fc-11eb-881c-d2885c4f98ff.png)

Do let me know if you require more information. Thanks in advance!

**Comment by jeromekelleher** [comment]
Hi @msmscrz, welcome to the wonderful world of coding! I think maybe you've opened this issue on the wrong repo though?
