### ISSUE TITLE
Refactor to use the dict representation of tree sequence

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tszip#39]
Currently we're explicitly writing down the columns that we compress, leading to loss of data when we have format updates in tskit. We should use the dict representation of the tables instead, and automatically create Column objects for the data with good default compression options. We can make some special cases for particular columns if we like, but we should by default always store all the data that comes from the input tree sequence.

related to #35

**Comment by brianzhang01** [comment]
If the format of written tsz files becomes different, it would be good to offer scripts to update old tsz files to this new format.

**Comment by jeromekelleher** [comment]
We'll try to keep the same format if possible @brianzhang01, but if there's a different format needed we'll make sure the old ones are also transparently supported (so there's no need for format upgrades).
