### ISSUE TITLE
Handle multiple input files with compressing to stdout

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tszip#63]
We're not quite handling this properly at the moment:

https://github.com/tskit-dev/tszip/pull/53#issuecomment-1042975806

@aabiddanda would you mind giving an example of what's happening here please?

**Comment by jeromekelleher** [comment]
I think the simplest thing is to raise an error for now, and if someone comes along wanting the feature we can implement it later?

**Comment by aabiddanda** [comment]
Seems like the most reasonable solution to me. I'll setup a small PR to raise the error.

**Comment by jeromekelleher** [comment]
SGTM, thanks @aabiddanda
