### ISSUE TITLE
Docs should be transferred from readthedocs

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tszip#67]
To match other tskit projects

**Comment by jeromekelleher** [comment]
Agreed, good to promote this tool more it's very handy!

**Comment by jeromekelleher** [comment]
Is this in the pipeline now @benjeffery?

**Comment by benjeffery** [comment]
The docs have been on the main site for a while. I'm just adding the redirects now.

**Comment by benjeffery** [comment]
Redirects are live

**Comment by hyanwong** [comment]
@benjeffery: the redirects aren't allowing links to the "stable" build, e.g. `https://tskit.dev/tszip/docs/stable/objects.inv`, which means that the tutorial build is failing (because it requires that link above to work)
