### ISSUE TITLE
cannot write to stdout

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/tszip#71]
I installed tszip via conda, and -c (and --stdout) are not recognized as arguments

I tried:
tszip -c test.ts

usage: tszip [-h] [-V] [-v] [--variants-only] [-S SUFFIX] [-k] [-f] [-d | -l]
             files [files ...]
tszip: error: unrecognized arguments: -c

**Comment by jeromekelleher** [comment]
Can you give us the version of tszip you get please?

```
$ tszip --version
```

**Comment by ShyamieG** [comment]
The tszip version I'm using is 0.1.0. It is the version I got by installing today via:

conda install -c "conda-forge/label/cf202003" tszip

**Comment by jeromekelleher** [comment]
Ah - try
```
conda install -c conda-forge tszip
```
I'm not sure why the other non-standard label is suggested. Did you see this on the tszip anaconda site or somewhere else?

**Comment by ShyamieG** [comment]
on anaconda.org

I tried the way you suggested first, but the install was failing for some reason...

Anyway, thanks for your help! I'll work on getting the latest version.
