### ISSUE TITLE
requires-python should be 3.9

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tszip#86]
We currently have ``requires-python = ">=3.8"`` in pyproject.toml. Should be 3.9, right?

**Comment by jeromekelleher** [comment]
Probably worth pushing out another release including this and #85 , once the docs build is fixed

**Comment by benjeffery** [comment]
Whoops, yep. Will correct.

**Comment by benjeffery** [comment]
Fixed by #88
